/*
|  .d8888b.                    888
| d88P  Y88b                   888
| 888    888                   888
| 888        888  888 .d8888b  888888 .d88b.  88888b.d88b.
| 888        888  888 88K      888   d88""88b 888 "888 "88b
| 888    888 888  888 "Y8888b. 888   888  888 888  888  888
| Y88b  d88P Y88b 888      X88 Y88b. Y88..88P 888  888  888
|  "Y8888P"   "Y88888  88888P'  "Y888 "Y88P"  888  888  888
|
|
|  .d8888b.  888          888    888
| d88P  Y88b 888          888    888
| 888    888 888          888    888
| 888        888  .d88b.  888888 88888b.   .d88b.  .d8888b
| 888        888 d88""88b 888    888 "88b d8P  Y8b 88K
| 888    888 888 888  888 888    888  888 88888888 "Y8888b.
| Y88b  d88P 888 Y88..88P Y88b.  888  888 Y8b.          X88
|  "Y8888P"  888  "Y88P"   "Y888 888  888  "Y8888   88888P'
|
*/

// Namespace
if (setup.clothes === null || setup.clothes === undefined) {
  setup.clothes = {} as setupClothes;
}

setup.clothes.defineCustomClothes = function(): void {
  // To specify items like starting clothing that aren't procedurally generated
  const items = {
    tttt: {
      key : "tttt",
      nick : "Thin Pajama Pants",
      type : "pants",
      slot : "bottom",
      colorWord : "pink",
      styleWord : "pajama pants",
      subStyleWord : "thin",
      tertiaryWord : "na",
      fabricWord : "satin",
      atr : 0,
      sexy : 1,
      formal : -4,
      exposure : 25,
      flag : {text: "Given to you by Lily"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 0,
      subStyle : 0,
      fabric : 0,
      color : 2,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : true,
      athletic : false,
      kinky : false,
      accessNip : false,
      accessPussy : false,
      accessButt : false,
      accessTits : true,
      accessAss : true,
      wear : ["normal", "off", "pulledDown"],
    },
    tttv: {
      key : "tttv",
      nick : "Thin Pajama Top",
      type : "top",
      slot : "top",
      colorWord : "pink",
      styleWord : "pajama shirt",
      subStyleWord : "thin",
      tertiaryWord : "long-sleeves",
      fabricWord : "satin",
      atr : 1,
      sexy : 1,
      formal : -4,
      exposure : 25,
      flag : {text: "Given to you by Lily"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 0,
      subStyle : 0,
      fabric : 0,
      color : 2,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : true,
      athletic : false,
      kinky : false,
      accessNip : true,
      accessPussy : true,
      accessButt : true,
      accessTits : false,
      accessAss : false,
      wear : ["normal", "off", "halfButton", "unbuttoned"],
    },
    tttw: {
      key : "tttw",
      nick : "Secondhand Bikini Top",
      type : "swimTop",
      slot : "bra",
      colorWord : "blue",
      styleWord : "bikini top",
      subStyleWord : "partial-coverage",
      tertiaryWord : "na",
      fabricWord : "nylon",
      atr : 2,
      sexy : 2,
      formal : -4,
      exposure : 15,
      flag : {text: "Given to you by Lily"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 0,
      subStyle : 0,
      fabric : 0,
      color : 10,
      origin : "Starter",
      price : 0,
      swimwear : true,
      nightwear : false,
      athletic : false,
      kinky : false,
      accessNip : false,
      accessPussy : true,
      accessButt : true,
      accessTits : true,
      accessAss : true,
      wear : ["normal", "off", "titsOut", "pulledDown", "pulledUp", "untied"],
    },
    tttx: {
      key : "tttx",
      nick : "Secondhand Bikini Bottom",
      type : "swimBottom",
      slot : "panties",
      colorWord : "blue",
      styleWord : "bikini bottom",
      subStyleWord : "regular",
      tertiaryWord : "na",
      fabricWord : "nylon",
      atr : 1,
      sexy : 1,
      formal : -4,
      exposure : 25,
      flag : {text: "Given to you by Lily"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 5,
      subStyle : 0,
      fabric : 0,
      color : 10,
      origin : "Starter",
      price : 0,
      swimwear : true,
      nightwear : false,
      athletic : false,
      kinky : false,
      accessNip : true,
      accessPussy : false,
      accessButt : true,
      accessTits : true,
      accessAss : false,
      wear : ["normal", "off", "pulledDown", "untied"],
    },
    tttz: {
      key : "tttz",
      nick : "Lily's Sweatpants",
      type : "sportBottom",
      slot : "bottom",
      colorWord : "light grey",
      styleWord : "sweatpants",
      subStyleWord : "baggy",
      tertiaryWord : "na",
      fabricWord : "cotton",
      atr : -1,
      sexy : 0,
      formal : -4,
      exposure : 0,
      flag : {text: "Given to you by Lily"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 1,
      subStyle : 0,
      fabric : 0,
      color : 20,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : true,
      kinky : false,
      accessNip : true,
      accessPussy : false,
      accessButt : false,
      accessTits : true,
      accessAss : false,
      wear : ["normal", "off", "pulledDown"],
    },
    ttvt: {
      key : "ttvt",
      nick : "Lily's Sweatshirt",
      type : "sportTop",
      slot : "top",
      colorWord : "light grey",
      styleWord : "sweatshirt",
      subStyleWord : "baggy",
      tertiaryWord : "na",
      fabricWord : "cotton",
      atr : -1,
      sexy : -1,
      formal : -4,
      exposure : 0,
      flag : {text: '"PROPERTY OF: YOUR MOM" is printed on the front'},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 1,
      subStyle : 0,
      fabric : 0,
      color : 20,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : true,
      kinky : false,
      accessNip : false,
      accessPussy : true,
      accessButt : true,
      accessTits : false,
      accessAss : true,
      wear : ["normal", "off", "pulledUp"],
    },
    ttvv: {
      key : "ttvv",
      nick : "Hospital Panties",
      type : "panties",
      slot : "panties",
      colorWord : "beige",
      styleWord : "classic briefs",
      subStyleWord : "regular",
      tertiaryWord : "na",
      fabricWord : "cotton",
      atr : -5,
      sexy : 0,
      formal : 0,
      exposure : 0,
      flag : {text: "An ugly not-quite-disposable hospital garment"},
      damage : 2,
      cond : {},
      dirty : 1,
      wetness : 0,
      style : 1,
      subStyle : 0,
      fabric : 0,
      color : 0,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : false,
      kinky : false,
      accessNip : true,
      accessPussy : false,
      accessButt : true,
      accessTits : true,
      accessAss : false,
      wear : ["normal", "off", "pulledDown"],
    },
    ttvw: {
      key : "ttvw",
      nick : "Hospital Sweatpants",
      type: "sportBottom",
      slot: "bottom",
      colorWord: "light grey",
      styleWord: "sweatpants",
      subStyleWord: "baggy",
      tertiaryWord: "na",
      fabricWord: "cotton",
      atr: -1,
      sexy: 0,
      formal: -4,
      exposure: 0,
      flag : {text: "Given to you by the hospital"},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 1,
      subStyle : 0,
      fabric : 0,
      color : 20,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : true,
      kinky : false,
      accessNip : true,
      accessPussy : false,
      accessButt : false,
      accessTits : true,
      accessAss : false,
      wear : ["normal", "off", "pulledDown"],
    },
    ttvx: {
      key : "ttvx",
      nick : "Hospital Sweatshirt",
      type: "sportTop",
      slot: "top",
      colorWord: "light grey",
      styleWord: "sweatshirt",
      subStyleWord: "baggy",
      tertiaryWord: "na",
      fabricWord: "cotton",
      atr: -1,
      sexy: -1,
      formal: -4,
      exposure: 0,
      flag : {text: '"AppleCare Cares" is printed on the front'},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 1,
      subStyle : 0,
      fabric : 0,
      color : 20,
      origin : "Starter",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : true,
      kinky : false,
      accessNip : false,
      accessPussy : true,
      accessButt : true,
      accessTits : false,
      accessAss : true,
      wear : ["normal", "off", "pulledUp"],
    },
    tvvv: { // what are these demonic 4 letter riddles?
      key : "tvvv",
      nick : "Maid dress",
      type : "dress",
      slot : "top",
      colorWord : "black",
      styleWord : "dress",
      subStyleWord : "maid",
      tertiaryWord : "na",
      fabricWord : "cotton",
      atr : 3,
      sexy : 4,
      formal : 15,
      exposure : 5,
      flag : {text: 'Work uniform"'},
      damage : 0,
      cond : {},
      dirty : 0,
      wetness : 0,
      style : 666,
      img: "IMG-CID-Maid",
      subStyle : 0,
      fabric : 0,
      color : 8,
      origin : "Maid Pouffiasse",
      price : 0,
      swimwear : false,
      nightwear : false,
      athletic : false,
      kinky : false,
      accessNip : false,
      accessPussy : true,
      accessButt : true,
      accessTits : false,
      accessAss : true,
      wear : ["normal", "off", "pulledUp"],
    },
  };
  const keys = Object.keys(items);
  for (let i = 0, c = keys.length; i < c; i++) {
    aw.clothes[keys[i]] = new Garment(items[keys[i]]);
  }
};

