setup.defineFixedNPCs = function() {
  function defineLily() {
    const npc: NPCinputData = {
      body: {},
      main: {},
      sched: {},
      bground: {},
      rship: {},
      sex: {},
      flags: {},
      friends: [],
      clothes: {},
      status: {},
      cond: {},
      outfit: {},
      mutate: {},
      pref: {},
      core: {},
      fert: {},
      makeout: [],
    };
    npc.body = {
      race: "white",
      skinColor: "fair",
      eyeColor: "light blue",
      hairColor: "strawberry blonde",
      hairCurl: 1,
      pubeColor: "dark blonde",
      height: 66,
      tone: 3,
      weight: 4,
      ass: 4,
      shoulders: 2,
      hips: 5,
      waist: 3,
      pubes: "triangular",
      hairdye: "none",
      tits: {
        size: 900,
        band: 36,
        cupNum: 21,
        cupRaw: 24,
        cup: "G-cup",
        bra: "34G",
        shape: "perky",
        nipple: "normal",
        lact: {on: false, max: 1050, size: 900, cupNum: 21, cup: "G-cup", bra: "34G"},
        nipLength: 2,
        nipGirth: 4,
        areola: 3,
        puffy: 3,
      },
      lactation: 3,
      lactCapacity: 300,
      pussy: {
        virgin: false,
        tight: 2,
        stretch: 0,
        wetness: 3,
        time: 0,
        tags: ["none"],
      },
      clit: 1,
      labia: 3,
      asshole: {
        virgin: true,
        tight: 1,
        stretch: 0,
        wetness: 0,
        time: 0,
        tags: ["none"],
      },
      cock: {
        length: 61,
        girth: 21,
        head: "normal",
        circum: false,
        hard: 4,
        smegma: false,
        tags: ["girthy"],
      },
      balls: {
        count: 2,
        size: 19,
        hang: 0,
        sac: 1,
        tags: ["none"],
      },
      beauty: 4,
      face: "cute",
      jaw: "normal",
      nose: "normal",
      ears: "pierced",
      brow: "normal",
      orgasm: 20,
      energy: 12,
      ATR: 10,
      topATR: 5,
      bottomATR: 5,
      tags: ["none"],
      makeup: {},
    };
    npc.main = {
      id: 101,
      age: 29,
      bd: [7, 2, 7, 2003],
      female: true,
      male: true,
      genes: "XXY",
      seen: true,
      interact: true,
      relation: true,
      lifetime: 0,
      tags: ["fixed", "plot"],
      name: "Lily",
      surname: "Richards",
      nickname: "Lils",
      portrait: "[img[IMG_NPC_Lily]]",
    };
    npc.sched = {
      workdays: [true, true, true, true, true, false, false],
      workhours: [8, 17],
      workLoc: "institute",
      outhours: [0, 3],
      locations: [],
    };
    npc.bground = {
      hschool: true,
      college: true,
      associate: true,
      bachelor: true,
      master: true,
      doctor: true,
      inschool: false,
      education: 6,
      homeParents: false,
      wealth: 2,
      cash: 3820,
      bank: 6925,
      debt: 420,
      home: 9,
      job: "Institute scientist",
      car: ["Sukayu", "Impregna", "new"],
      timeApple: 2,
      sister: 0,
      sisterYounger: false,
      brother: 0,
      brotherYounger: false,
      stepParent: "na",
      dadDead: false,
      momDead: true,
      married: false,
      exSpouse: 0,
    };
    npc.rship = {
      friend: true,
      acquaint: true,
      dating: false,
      lovers: false,
      exclusive: false,
      engaged: false,
      married: false,
      likePC: 90,
      likeNPC: 90,
      lovePC: 80,
      loveNPC: 80,
      companion: 0,
      domsub: 70,
      mesh: 0,
      daysince: 0,
      space: 0,
      dates: 0,
      hangout: 0,
      met: 0,
      sleptover: 0,
      pcslept: 0,
    };
    npc.sex = {
      makeout: 0,
      sex: 0,
      oral: 0,
      anal: 0,
      public: 0,
      domsub: 0,
      forced: 0,
      creampie: 0,
      accidentCP: 0,
      unprotected: 0,
      nocumNPC: 0,
      nocumPC: 0,
      saboPCbc: 0,
      caughtSabo: 0,
      PCsaboBC: 0,
      PCsaboCaught: 0,
      sexlocs: ["none"],
      tags: ["none"],
    };
    npc.friends = ["none"];
    npc.clothes = {
      empty: true,
    };
    npc.status = {
      birthCon: 87,
      birthConType: "patch",
      // tslint:disable-next-line:max-line-length
      bc: { dia: false, diaType: "none", diaEf: 0, diaHealth: 0, diaBreak: false, diaSab: 0, femCon: false, femConHealth: 0, femConEf: 0, femConType: "none", femConBreak: false, femConSab: 0, menCup: false, menCupType: "none", menCupHealth: 0, menCupEf: 0, menCupBreak: false, menCupSab: 0, sponge: false, spongeType: "none", spongeEf: 0, spongeSab: 0, condom: false, condomType: "none", condomHealth: 0, condomEf: 0, condomBreak: false, condomSab: 0, headCap: false, headCapType: "none", headCapHealth: 0, headCapEf: 0, headCapBreak: false, headCapSab: 0 },
      alcohol: 0,
      drugs: [0, 0, 0, 0, 0],
      fertText: "on the patch",
      status: [],
      risk: 0,
      wombA: {
        preg: false,
        know: false,
        weeks: 0,
        days: 0,
        birth: 0,
        count: 0,
      },
      wombB: {
        preg: false,
        know: false,
        weeks: 0,
        days: 0,
        birth: 0,
        count: 0,
      },
      period: false,
      milk: 0,
      milkStore: 0,
      arousal: 2,
      pleasure: 0,
      satisfaction: 38,
      need: 0,
      ATR: 12,
      stress: 82,
      happy: 1,
      anger: 0,
      lonely: 22,
      fatigue: 0,
      asleep: false,
      health: 99,
      knowBCfail: false,
      BCfail: false,
      overAnger: false,
      overStress: false,
      overDepress: false,
      underSat: false,
      addictMax: 12,
      jonesing: 0,
      withdrawl: false,
      energy: 9,
      energyRegen: true,
      clean: 1,
      injury: [0],
      disease: [0],
      diseaseRate: 9,
      bored: 5,
      addict: {
        sex: 6,
        alco: 2,
        heat: 0,
        satyr: 0,
        focus: 12,
        cum: 8,
        zone: 9,
        cream: 1,
      },
      addictNeed: {
        sex: 0,
        alco: 0,
        heat: 0,
        satyr: 0,
        focus: 0,
        cum: 0,
        zone: 0,
        cream: 0,
      },
    };
    npc.cond = {
      hair: [1, "A", "A"],
      face: [1, "A", "A"],
      chest: [1, "A", "A"],
      back: [1, "A", "A"],
      hands: [1, "A", "A"],
      belly: [1, "A", "A"],
      butt: [1, "A", "A"],
      pubis: [1, "A", "A"],
      anus: [1, "A", "A"],
      anusFluid: 0,
      vagina: [1, "A", "A"],
      vagFluid: 0,
      cock: [1, "A", "A"],
      legs: [1, "A", "A"],
      feet: [1, "A", "A"],
    };
    npc.outfit = {
      empty: true,
    };
    npc.mutate = {
      Milk: false,
      Acid: false,
      BC: false,
      Multiple: false,
      Gestate: false,
      Cycle: false,
      TwinWomb: false,
      Pheromone: false,
      Period: false,
      Immune: false,
      Mouth: false,
      Contort: false,
      Cumpire: false,
      PseudoPreg: false,
      Elastic: false,
      LitePhero: false,
      MegaNuts: false,
      Multgasm: false,
      PowerEjac: true,
      AcidPre: true,
    };
    npc.pref = {
      Fweight: [-2, -2, 0, 2, 0, -2],
      Mweight: [-2, -2, 1, 1, -1, -2],
      Fheight: [0, 1, 2, 1, 0],
      Mheight: [-2, -2, 0, 1, -1],
      Fmuscle: [-2, -2, 1, 2, -1, -2],
      Mmuscle: [-2, -2, 0, 2, 0, -2],
      Fother: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      Mother: [0, 0, 0, 0, 0, 0, 0, 0, 0],
      active: 1,
      romance: 2,
      novel: 3,
      excite: 1,
      night: 2,
      expensive: -1,
      fancy: -1,
      popular: -2,
      // tslint:disable-next-line:max-line-length
      position: ["facetoface", "cowgirl", "missionary", "doggy", "speedbump", "spoon", "squat", "reversecowgirl", "sides", "standing"],
      sexact: ["vaginal", "anal", "recOral", "giveOral", "makeout", "recHand", "giveHand"],
      kinks: ["risky", "cumSlut", "liberate", "dom", "nips"],
    };
    npc.core = {
      will: 3,
      libido: 5,
      open: 3,
      vert: 2,
      perv: 22,
      corrupt: 15,
      diq: 9,
      iq: 147,
      bimbo: 0,
      op: true,
      cl: false,
      intro: true,
      extro: false,
      sexuality: 1,
      straight: false,
      bi: true,
      homo: false,
      procreate: {
        str: 3,
        secure: -3,
        preg: 1,
        kids: -1,
        evolve: 2,
        pleasure: 2,
      },
      morality: {
        str: 3,
        life: 1,
        liberty: 3,
        property: 1,
        honesty: -1,
        integrity: 2,
      },
      agreeable: {
        str: 2,
        interest: -1,
        empathy: 1,
        caring: 2,
        trust: -1,
        altruism: 2,
      },
      conscient: {
        str: 4,
        thoughtful: 2,
        responsible: 3,
        attention: 3,
        trustworthy: 1,
        structure: -1,
      },
      loyalty: {
        str: 4,
        betrayal: 2,
        cheating: 1,
        effort: 2,
        permanence: 3,
        family: 3,
      },
      curiosity: {
        str: 5,
        complex: 3,
        learning: 3,
        abstract: 3,
        curiosity: 2,
        novelty: 2,
      },
      neurotic: {
        str: 3,
        impulsive: 2,
        unstable: -2,
        addiction: -2,
        anxiety: 1,
        sensitive: -1,
        anger: -2,
        sadness: 2,
      },
      ego: {
        str: 2,
        selfinterest: -1,
        selfworth: 2,
        confidence: 1,
        fragility: -1,
        selfimage: 2,
        mach: 2,
        risk: -1,
      },
    };
    npc.fert = {
      barren: false,
      egg: 17,
      implant: 10,
      vagHostility: 14,
      cycle: 26,
      cycStart: [random(1, 7), random(1, 4)],
      ovuMod: randomDist([2, 3, 3, 4, 3, 3, 2]) - 4,
      period: 3,
      multEgg: 12,
      wombHealth: 0,
      iud: false,
      pregTerm: 34,
      fertility: 5,
      flagF: ["none"],
      quality: 10,
      ejac: 30,
      resMax: 58,
      reserve: 55,
      refract: 6,
      quantity: 20,
      surv: 5,
      flagM: ["none"],
    };
    npc.flags = {
      other: ["none"],
      knows: ["none"],
      rumor: ["none"],
      exes: ["none"],
      kids: 0,
      kidsPC: 0,
      toys: false,
      toysPublic: false,
      knowPCpreg: false,
      isFather: false,
      thinkFather: false,
      knowsAcidVag: true,
      openRship: false,
    };
    npc.info = {
      bodyGeneral: true,
      bodyJunk: true,
      bodyTits: true,
      bodyDetail: false,
      status: 3,
      fert: 1,
      trait: 3,
      kink: 2,
      mutate: false,
      core: 2,
      pref: 2,
      sched: true,
      bGround: 3,
    };
    const pName = "n101";
    try {
      // tslint:disable-next-line:max-line-length
      const npcData = setup.npcDataFormat(npc);
      // npc.body, npc.main, npc.sched, npc.bground, npc.rship, npc.sex, npc.flags, npc.friends, npc.clothes, npc.status, npc.cond, npc.outfit, npc.mutate, npc.pref, npc.core, npc.fert, npc.makeout
      aw.npc[pName] = new NPC(npcData);
    } catch (er) {
      const ermsg = "Error with NPC constructor for NPCID:" + pName + " error: " + er;
      console.log(ermsg);
      UI.alert(ermsg);
    }
    try {
      setup.npc.ready.push(pName);
      setup.npc.acquainted.push(pName);
      setup.npc.friends.push(pName);
      // setup.npc.lover.push(pName);
      setup.npc.interested.push(pName);
      setup.npc.age28to33.push(pName);
      setup.npc.futa.push(pName);
      setup.npc.single.push(pName);
    } catch (e) { aw.con.error("some strange error with setup.npc...", e); }
  }
/*********************************************************************************
.    ████████╗ ██████╗ ██████╗ ██╗   ██╗
.    ╚══██╔══╝██╔═══██╗██╔══██╗╚██╗ ██╔╝
.       ██║   ██║   ██║██████╔╝ ╚████╔╝
.       ██║   ██║   ██║██╔══██╗  ╚██╔╝
.       ██║   ╚██████╔╝██████╔╝   ██║
.       ╚═╝    ╚═════╝ ╚═════╝    ╚═╝
**********************************************************************************/
  function defineToby() {
    const npc: NPCinputData = {
      body: {},
      main: {},
      sched: {},
      bground: {},
      rship: {},
      sex: {},
      flags: {},
      friends: [],
      clothes: {},
      status: {},
      cond: {},
      outfit: {},
      mutate: {},
      pref: {},
      core: {},
      fert: {},
      makeout: [],
    };
    npc.body = {
      race: "white",
      skinColor: "fair",
      eyeColor: "blue",
      hairColor: "brown",
      hairCurl: 1,
      pubeColor: "black",
      height: 72,
      tone: 5,
      weight: 3,
      ass: 2,
      shoulders: 5,
      hips: 2,
      waist: 3,
      pubes: "trimmed",
      hairdye: "none",
      tits: {
        shape: "flat",
        nipple: "normal",
        nipLength: 3,
        nipGirth: 1,
        areola: 1,
        puffy: 1,
        band: 0,
        silicone: 0,
        base: {
          bra: 0,
          cup: 0,
          cupNum: 0,
          cupRaw: 0,
          size: 0,
        },
        lact: {
          on: false,
          max: 0,
          size: 0,
          cupNum: 0,
          cup: 0,
          bra: 0,
        },
      },
      lactation: 0,
      lactCapacity: 0,
      pussy: {
        virgin: true,
        tight: -1,
        stretch: -1,
        time: -1,
        wetness: -1,
        tags: [],
      },
      clit: 0,
      labia: 0,
      asshole: {
        virgin: true,
        tight: 1,
        stretch: 0,
        wetness: 0,
        time: 0,
        tags: ["none"],
      },
      cock: {
        length: 76,
        girth: 28,
        head: "normal",
        circum: false,
        hard: 4,
        smegma: false,
        tags: ["girthy"],
      },
      balls: {
        count: 2,
        size: 26,
        hang: 0,
        sac: 1,
        tags: ["none"],
      },
      beauty: 4,
      face: "normal",
      jaw: "normal",
      nose: "normal",
      ears: "normal",
      brow: "normal",
      orgasm: 30,
      energy: 16,
      ATR: 10,
      topATR: 5,
      bottomATR: 5,
      tags: ["none"],
      makeup: {},
    };
    npc.main = {
      id: 102,
      age: 24,
      bd: [5, 1, 5, 2003],
      female: false,
      male: true,
      genes: "XY",
      seen: true,
      interact: true,
      relation: true,
      lifetime: 0,
      tags: ["fixed", "plot"],
      name: "Toby",
      surname: "Jones",
      nickname: "Toby",
      portrait: "[img[IMG-npc-TobyJones]]",
    };
    npc.sched = {
      workdays: [true, true, true, true, true, false, false],
      workhours: [8, 17],
      workLoc: "institute",
      outhours: [0, 3],
      locations: [],
    };
    npc.bground = {
      hschool: true,
      college: true,
      associate: true,
      bachelor: true,
      master: false,
      doctor: false,
      inschool: false,
      education: 4,
      homeParents: true,
      wealth: 2,
      cash: 1620,
      bank: 3525,
      debt: 1420,
      home: 5,
      job: "Institute Office Clerk",
      car: ["Toyoda", "Priapism", "used"],
      timeApple: 2,
      sister: 0,
      sisterYounger: false,
      brother: 0,
      brotherYounger: false,
      stepParent: "na",
      dadDead: true,
      momDead: false,
      married: false,
      exSpouse: 0,
    };
    npc.rship = {
      friend: true,
      acquaint: true,
      dating: false,
      lovers: false,
      exclusive: false,
      engaged: false,
      married: false,
      likePC: 75,
      likeNPC: 75,
      lovePC: 40,
      loveNPC: 55,
      companion: 0,
      domsub: 70,
      mesh: 0,
      daysince: 0,
      space: 0,
      dates: 0,
      hangout: 0,
      met: 0,
      sleptover: 0,
      pcslept: 0,
    };
    npc.sex = {
      makeout: 0,
      sex: 0,
      oral: 0,
      anal: 0,
      public: 0,
      domsub: 0,
      forced: 0,
      creampie: 0,
      accidentCP: 0,
      unprotected: 0,
      nocumNPC: 0,
      nocumPC: 0,
      saboPCbc: 0,
      caughtSabo: 0,
      PCsaboBC: 0,
      PCsaboCaught: 0,
      sexlocs: ["none"],
      tags: ["none"],
    };
    npc.friends = ["none"];
    npc.clothes = {
      empty: true,
    };
    npc.status = {
      birthCon: 0,
      birthConType: "patch",
      // tslint:disable-next-line:max-line-length
      bc: { dia: false, diaType: "none", diaEf: 0, diaHealth: 0, diaBreak: false, diaSab: 0, femCon: false, femConHealth: 0, femConEf: 0, femConType: "none", femConBreak: false, femConSab: 0, menCup: false, menCupType: "none", menCupHealth: 0, menCupEf: 0, menCupBreak: false, menCupSab: 0, sponge: false, spongeType: "none", spongeEf: 0, spongeSab: 0, condom: false, condomType: "none", condomHealth: 0, condomEf: 0, condomBreak: false, condomSab: 0, headCap: false, headCapType: "none", headCapHealth: 0, headCapEf: 0, headCapBreak: false, headCapSab: 0 },
      alcohol: 0,
      drugs: [0, 0, 0, 0, 0],
      fertText: "none",
      status: [],
      risk: 0,
      wombA: {
        preg: false,
        know: false,
        weeks: 0,
        days: 0,
        birth: 0,
        count: 0,
      },
      wombB: {
        preg: false,
        know: false,
        weeks: 0,
        days: 0,
        birth: 0,
        count: 0,
      },
      period: false,
      milk: 0,
      milkStore: 0,
      arousal: 2,
      pleasure: 0,
      satisfaction: 38,
      need: 0,
      ATR: 12,
      stress: 82,
      happy: 1,
      anger: 0,
      lonely: 22,
      fatigue: 0,
      asleep: false,
      health: 99,
      knowBCfail: false,
      BCfail: false,
      overAnger: false,
      overStress: false,
      overDepress: false,
      underSat: false,
      addictMax: 12,
      jonesing: 0,
      withdrawl: false,
      energy: 9,
      energyRegen: true,
      clean: 1,
      injury: [0],
      disease: [0],
      diseaseRate: 9,
      bored: 5,
      addict: {
        sex: 6,
        alco: 2,
        heat: 0,
        satyr: 0,
        focus: 12,
        cum: 2,
        zone: 9,
        cream: 1,
      },
      addictNeed: {
        sex: 0,
        alco: 0,
        heat: 0,
        satyr: 0,
        focus: 0,
        cum: 0,
        zone: 0,
        cream: 0,
      },
    };
    npc.cond = {
      hair: [1, "A", "A"],
      face: [1, "A", "A"],
      chest: [1, "A", "A"],
      back: [1, "A", "A"],
      hands: [1, "A", "A"],
      belly: [1, "A", "A"],
      butt: [1, "A", "A"],
      pubis: [1, "A", "A"],
      anus: [1, "A", "A"],
      anusFluid: 0,
      vagina: [1, "A", "A"],
      vagFluid: 0,
      cock: [1, "A", "A"],
      legs: [1, "A", "A"],
      feet: [1, "A", "A"],
    };
    npc.outfit = {
      empty: true,
    };
    npc.mutate = {
      Milk: false,
      Acid: false,
      BC: false,
      Multiple: false,
      Gestate: false,
      Cycle: false,
      TwinWomb: false,
      Pheromone: false,
      Period: false,
      Immune: false,
      Mouth: false,
      Contort: false,
      Cumpire: false,
      PseudoPreg: false,
      Elastic: false,
      LitePhero: false,
      MegaNuts: false,
      Multgasm: false,
      PowerEjac: true,
      AcidPre: true,
    };
    npc.pref = {
      Fweight: [-2, -2, 0, 2, 0, -2],
      Mweight: [-2, -2, 1, 1, -1, -2],
      Fheight: [0, 1, 2, 1, 0],
      Mheight: [-2, -2, 0, 1, -1],
      Fmuscle: [-2, -2, 1, 2, -1, -2],
      Mmuscle: [-2, -2, 0, 2, 0, -2],
      Fother: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      Mother: [0, 0, 0, 0, 0, 0, 0, 0, 0],
      active: 1,
      romance: 2,
      novel: 1,
      excite: 2,
      night: 2,
      expensive: -1,
      fancy: -1,
      popular: -2,
      // tslint:disable-next-line:max-line-length
      position: ["facetoface", "cowgirl", "missionary", "doggy", "speedbump", "spoon", "squat", "reversecowgirl", "sides", "standing"],
      sexact: ["vaginal", "anal", "recOral", "giveOral", "makeout", "recHand", "giveHand"],
      kinks: ["risky", "cumSlut", "liberate", "dom", "nips"],
    };
    npc.core = {
      will: 3,
      libido: 5,
      open: 1,
      vert: -2,
      perv: 22,
      corrupt: 15,
      diq: 1,
      iq: 101,
      bimbo: 32,
      op: false,
      cl: false,
      intro: false,
      extro: true,
      sexuality: 1,
      straight: true,
      bi: false,
      homo: false,
      procreate: {
        str: 3,
        secure: -3,
        preg: 1,
        kids: -1,
        evolve: 2,
        pleasure: 2,
      },
      morality: {
        str: 3,
        life: 1,
        liberty: 3,
        property: 1,
        honesty: -1,
        integrity: 2,
      },
      agreeable: {
        str: 2,
        interest: -1,
        empathy: 1,
        caring: 2,
        trust: -1,
        altruism: 2,
      },
      conscient: {
        str: 4,
        thoughtful: 2,
        responsible: 3,
        attention: 3,
        trustworthy: 1,
        structure: -1,
      },
      loyalty: {
        str: 4,
        betrayal: 2,
        cheating: 1,
        effort: 2,
        permanence: 3,
        family: 3,
      },
      curiosity: {
        str: 5,
        complex: 3,
        learning: 3,
        abstract: 3,
        curiosity: 2,
        novelty: 2,
      },
      neurotic: {
        str: 3,
        impulsive: 2,
        unstable: -2,
        addiction: -2,
        anxiety: 1,
        sensitive: -1,
        anger: -2,
        sadness: 2,
      },
      ego: {
        str: 2,
        selfinterest: -1,
        selfworth: 2,
        confidence: 1,
        fragility: -1,
        selfimage: 2,
        mach: 2,
        risk: -1,
      },
    };
    npc.fert = {
      barren: false,
      egg: 0,
      implant: 0,
      vagHostility: 0,
      cycle: 0,
      cycStart: [random(1, 7), random(1, 4)],
      ovuMod: 0,
      period: 0,
      multEgg: 0,
      wombHealth: 0,
      iud: false,
      pregTerm: 34,
      fertility: 5,
      flagF: ["none"],
      quality: 18,
      ejac: 60,
      resMax: 188,
      reserve: 142,
      refract: 8,
      quantity: 28,
      surv: 5,
      flagM: ["none"],
    };
    npc.flags = {
      other: ["none"],
      knows: ["none"],
      rumor: ["none"],
      exes: ["none"],
      kids: 0,
      kidsPC: 0,
      toys: false,
      toysPublic: false,
      knowPCpreg: false,
      isFather: false,
      thinkFather: false,
      knowsAcidVag: true,
      openRship: false,
    };
    npc.info = {
      bodyGeneral: false,
      bodyJunk: false,
      bodyTits: false,
      bodyDetail: false,
      status: 3,
      fert: 1,
      trait: 3,
      kink: 2,
      mutate: false,
      core: 2,
      pref: 2,
      sched: true,
      bGround: 3,
    };
    const pName = "n102";
    try {
      // tslint:disable-next-line:max-line-length
      const npcData = setup.npcDataFormat(npc);
      // npc.body, npc.main, npc.sched, npc.bground, npc.rship, npc.sex, npc.flags, npc.friends, npc.clothes, npc.status, npc.cond, npc.outfit, npc.mutate, npc.pref, npc.core, npc.fert, npc.makeout
      aw.npc[pName] = new NPC(npcData);
    } catch (er) {
      const ermsg = "Error with NPC constructor for NPCID:" + pName + " error: " + er;
      console.log(ermsg);
      UI.alert(ermsg);
    }
    try {
      setup.npc.ready.push(pName);
      setup.npc.friends.push(pName);
      // setup.npc.lover.push(pName);
      setup.npc.interested.push(pName);
      setup.npc.age22to27.push(pName);
      setup.npc.male.push(pName);
      setup.npc.single.push(pName);
    } catch (e) { aw.con.error("some strange error with setup.npc...", e); }
  }



  defineLily();
  defineToby();

};
