/*
8888888b.  8888888b.  8888888888        d8888 888b     d888  .d8888b.
888  "Y88b 888   Y88b 888              d88888 8888b   d8888 d88P  Y88b
888    888 888    888 888             d88P888 88888b.d88888 Y88b.
888    888 888   d88P 8888888        d88P 888 888Y88888P888  "Y888b.
888    888 8888888P"  888           d88P  888 888 Y888P 888     "Y88b.
888    888 888 T88b   888          d88P   888 888  Y8P  888       "888
888  .d88P 888  T88b  888         d8888888888 888   "   888 Y88b  d88P
8888888P"  888   T88b 8888888888 d88P     888 888       888  "Y8888P"
*/

aw.dreams = {
  standard() {
    const dreams = [
      `<p>@@.head3;Y@@ou lay peacefully in your bed, your <<pcBoobSize>> chest rising and falling with your slow breathing. There is a sigh of wind and your sleeping form shivers slightly, your <<pcShoulderSize>> shoulders hunching slightly under the covers. A bony, almost skeletal hand comes to rest on your lower abdomen, just above <<if ↂ.pc.groom.pubeStyle === "smooth" || ↂ.pc.groom.pubeStyle === "shaved">>your smooth pubic mound.<<else>>your <<p pubestyle.q>> pubes.<</if>></p><p>@@.npc;Rest young one... There is so much in store for you...@@ A tingle of pleasure shoots up your spine. With an almost inaudible chuckle, the ancient presence is gone. You awaken with a start, looking around the room frantically as if expecting someone to be there. Seeing nothing out of the ordinary, you eventually calm down. @@.mono;It must've been a dream...@@ You force yourself to relax so you can go back to sleep. Eventually, you succeed.</p>`,
      `<p><<f Y>>ou stayed late at work today in order to try to get in better with your boss. You think you're the only one still working until a handsome young man rounds the corner. You're almost sure you know him, so when he grabs your waist you go limp in response. You feel his breath on your neck. His hands on your skin. With his right hand he pulls your undergarments from your body and slips his hand in deeper. As he does he kisses the back of your neck and you open your mouth and sigh. You want to see who this man is. You're sure he's someone you've met in Appletree. In a flash you decide to spin around and face him. You try, but soon find yourself falling out of bed. It seems you tried to spin around outside your dream too... Slightly more annoyed, you climb back into bed and go back to sleep.</p>`,
      `<p><<f b>>eing the famous explorer you are, you're climbing up K'coc Mountain, a large volcano located deep in the jungle. The volcano is shaped like a tall cylinder rather than a cone, though there is a rounded dome that makes up the peak. You and your party make your way up a perilous path that follows one of the volcano's many vein-like protuberances. Occasionally your group must leave the steep steps carved into the rock of the curving veins and make your way along wooden planks supported by metal rods hammered into the smooth stone.</p><p>Eventually you make it to the summit and lay your eyes on Se'Men Village. Many wooden shack-like buildings stand on short stilts atop the curved stone. While the structures seem ramshackle and inadequate for the temperatures at this altitude, you're still impressed that the villagers managed to haul so much timber up the long path you just climbed. As you make your way to the heart of the village, the few villagers you spot carefully ignore your small party of explorers.</p><p>There is a large oval pit filled with liquid at the center of the village, and though the liquid is clear you can't see the bottom. Numerous buckets and barrels surround the pit, while an older woman busies herself lowering a bucket on a rope to collect the liquid as if drawing water from a well. A teenage girl is drinking some of the thicker-than-water liquid from a bucket using a ladle. Suddenly the ground quakes beneath you. One of your party yells out suddenly @@.npc;The volcano! It's going to ejaculate!@@</p>`,
      `<p><<f a>> siren blares, amber warning lights strobe on the walls. The velocidickors are loose. You and a coworker are running down one of the countless underground tunnels, heading toward a set of double doors. You burst through the doors and emerge into a forest, the sudden change of scenery stopping you in your tracks. You have no idea where you are, and a quick glance at your coworker tells you he doesn't know either. @@.npc;Let's head east, worst case we'll end up at the highway. Come on.@@ He starts walking and you follow silently.</p><p>You hear a hissing sound, and two dickors bound out in front of you on their testicle leg things. Your coworker holds his hands up, trying to calm them as he slowly crouches. He picks up a stick and stands up. @@.npc;Wanna play fetch? Look, it's a stick!@@ The velocidickors show no sign of recognition. @@.npc;Stick stupid!@@ He throws the stick weakly past the dickors @@.npc;Fetch!@@. They don't move. Instead one of the phallic creatures seems to shiver and spits a thick wad of white goo from it's mouth urethra thing. It lands on your coworkers chest with a loud wet slap. With horror written on his face he wipes at the white splooge with his hand, smearing it and leaving thick strands hanging between his hand and chest. The second dickor starts shivering then, and the next load catches your coworker right in the face. He screams, and the two giant penises pounce on him.</p><p>You don't wait around to see what they're doing, instead, you dash off into the woods. You sprint as fast as your legs can carry you until you're totally winded. You rest, your hands on your knees as you struggle to catch your breath. Suddenly the leaves of the nearby bushes rustle and a large shivering cockhead emerges. @@.pc;Clever girl.@@ A thick wad of white goo slams into your face.</p>`,
      `<p><<f y>>our class is presenting their projects today, each of you were assigned a part of the male or female reproductive system to teach the rest of the class about. After watching the presentations of several of your classmates, you suddenly realize it's your turn to present. You pick up your project board with "Sperm Highway: The Fallopian Tubes" written neatly in large pink letters. Making your way to the front of the class, you set the project board on the teacher's desk and psych yourself up to present your lesson.</p><p>That's when the laughter starts. Your classmates are all laughing, some pointing in your direction. You glance over at the teacher, she's holding her mouth and trying not to laugh. You look down and discover--to your complete surprise--that you're wearing an entire outfit of clothes. A blouse, a skirt, and you can even feel a bra and panties underneath. Someone shouts @@.npc;You going to a funeral after this or something?@@ Of course, your classmates and teacher are all nude as you'd expect. @@.mono;How'd I accidentally put on clothes this morning!?@@</p>`,
      `<p><<f y>>ou're eating in a scary red restaurant. For some reason, the waitstaff is forcing everyone to sit on the floor, there are no chairs or tables. Suddenly the other patrons start screaming. You look around frantically and see giant macaroni noodles emerging from the floor like sandworms swimming through the floor. One of the giant noodles bites a man's head off. The screaming intensifies, but for some reason nobody gets up or tries to run away. The red blood matches the red on the walls and floor. Soon the macaroni will come for you too.</p>`,
    ];
    const x = random(0, dreams.length - 1);
    return dreams[x];
  },
  none() {
    return `<p>@@.head3;Y@@ou rest peacefully through the night. You likely have many dreams, but none that you still remember by the time you awake in the morning.</p>`;
  },
  unsatisfied() {
    const dreams = [
      `<p><<f y>>ou're standing in your bathroom when you suddenly realize that you're extremely horny. You're totally naked, and when you look down you notice that your cunt is pouring femlube out like a literal faucet. It's splashing against the tile floor, and has already soaked your legs. You stare in amazement as your throbbing pussy continues to pour its juices without stop. You aren't sure how long you were simply staring, but you realize that the slippery liquid is flooding the room. Your feet are already under the surface of the warm nectar. In a panic you try to open the door to the bathroom, but to your dismay it seems to be locked. While you struggle with the door the flood of your fluids grows even deeper; it reaches your shins by the time you give up.</p><p>@@.mono;I'm going to drown at this rate!@@ You begin to panic as the level of slippery liquid reaches your knees. @@.mono;That's it! I just need to cum! If I cum and get rid of this arousal, I'll stop leaking so much.@@ You lean against the counter and frantically use both hands to play with yourself. You focus on rubbing your clit with one hand while the other plunges two fingers into your depths. It feels good--really good--but you can't help but notice that the pleasure has caused your pussy to start spraying out lube like a firehose. You don't have time to wonder how such a feat is even possible, as the level of lube reaches the top of your sink. Suddenly your legs slip out from under you and you splash into the hot liquid. Your mouth is flooded with your taste, and you struggle to swim your way upward. When your face finally breaks the surface and you're able to fill your burning lungs, you realize that the room is now almost entirely full of your juices. You tilt your head back to reach the small gap of air beneath the ceiling, but in only moments that's gone too.</p><p>Just as you think you're about to drown, you suddenly wake up. You throw off the pillow that somehow ended up on your face and catch your breath. You can feel a slick moisture between your legs, and realize that you've probably made a mess of your bedsheets. @@.mono;I really need to get laid...@@</p>`,
      `You're awoken by the sound of high-pitched sobbing. You sit up and turn on your nightstand light, looking toward the sound of the crying. The only thing you notice is Mr. Pink, quivering atop the nightstand beside you. <<if $AW.startMale>>Mr. Pink was your ex's first dildo, a realistically-shaped toy made of pink material. She shared a sort of strange relationship with it, almost like a childhood stuffed animal, which you always thought was a little strange.<<else>>Mr. Pink was your very first dildo, a realistically-shaped toy made of pink material. You got him while you were a teenager, and over time you can to treat him like a treasured stuffed animal.<</if>> @@.pc;Mr. Pink?@@ The dildo wobbles on his two half-ball feet as he turns to face you. You can tell he's been crying, a beaded tear still trembles atop his head. @@.pc;What's wrong Mr. Pink?@@<p>@@.npc;You haven't used me in forever... I can't go on this way.@@ Only then do you notice that a string is wrapped around him--just under his head--tied into a noose. You follow the string with your eyes, seeing that it ends in a tampon that's wedged into your nightstand drawer. @@.npc;Goodbye <<name>>, I loved your pussy.@@ With that Mr. Pink throws himself from the nightstand. His fall is brought to a sudden stop by the string with an unsettling crack, two AA batteries suddenly tumble to the floor.</p>`,
    ];
    const x = random(0, dreams.length - 1);
    return dreams[x];
  },
  needy() {
    return aw.dreams.unsatisfied();
  },
  preg() {
    const dreams = [
      `<p><<f y>>ou're surrounded by giant fruit, or perhaps you're just very small. You don't bother to ponder the difference because you're very hungry. You dive at a slice of peach nearby, and begin eating. You eat and eat, eventually finishing the giant slice of fruit. Despite the fact that you must've eaten half your body mass in peach, you're still ravenous. You run over to a colossal slice of honeydew and scoop out a handful. You keep eating and eating...</p>`,
      `<p><<f y>>ou're so hungry that you take a giant bite of a waffle-headed person's head. A heavy stream of maple syrup sprays from the wound, and the man falls to the floor. He spasms a bit, and then stops moving. Cops with donut heads arrest you.</p><p>You stare in horror as a jury of waffle-headed people give their verdict: @@.npc;Guilty!@@ A waffle-headed woman holds two children close as they all cry butter tears. The bagel judge looks at you fiercely. @@.npd;Pop her cherry!@@ A cookie-headed bailiff approaches you with a giant needle. That's when you realize that your head is a cherry.</p>`,
    ];
    const x = random(0, dreams.length - 1);
    return dreams[x];
  },
  latePreg() {
    const dreams = [
      `<p><<f y>>our water breaks, and it's a mad dash to get to the hospital in time for delivery. You arrive without incident, thankfully, and the hospital staff are quick to take care of you. You're quickly changed into a hospital gown, and you're laid down on a birthing bed with your lower half exposed. @@.npc;Okay Miss <<surname>>, we're going to wheel you to the delivery room now.@@ As you're wheeled down the corridors, you're happy that the lower portion of the bed hasn't been split apart into an M shape with leg rests and stirrups. @@.mono;Then I'd be really exposed!@@</p><p>After rolling down what feels like a mile of hospital hallways, you arrive at a set of double doors with "Delivery Room" printed above them. When you pass through, however, you find that the chamber on the other side is more like an amphitheater than a hospital room. The stadium seating seems to be full to capacity, and you're rolled into the center of a flood of light from spotlights. It strongly reminds you of a circus ring, an impression only strengthened when a series of midgets in doctor's garb arrive to catch your babies.</p><p>You're distracted from the situation by the birthing pain, though it feels a lot less intense than you were expecting. Finally your first baby emerges and is caught by one of the midget doctors, who quickly clamps and cuts the umbilical cord and carries the baby off. The process repeats with the second baby and the third, again and again. You notice a lit score board off to the side. When it reads 26 you finally notice a suspenseful but comedic tune being played from somewhere. When the board reads 34, you suddenly realize. @@.mono;I'm a human clown car!@@</p>`,
    ];
    const x = random(0, dreams.length - 1);
    return dreams[x];
  },
};


