/*
..####...######...####...#####...######..........######..##..##..##..##.
.##........##....##..##..##..##..##................##....###.##..##..##.
..####.....##....##..##..#####...####..............##....##.###..##..##.
.....##....##....##..##..##..##..##................##....##..##...####..
..####.....##.....####...##..##..######..........######..##..##....##...
........................................................................
.......SETS VARIABLES USED TO CONTAIN STORE INVENTORY OBJECT KEYS.......
*/

// Generates clothing for all the clothing stores, replacing their inventory.
setup.generateStoreClothes = function(): void {
  let cheat = false;
  if (aw.chad.shop) {
    cheat = true;
  }
  const count = (cheat) ? 40 : 20;
  const halfCount = (cheat) ? 20 : 10;
  const countBig = (cheat) ? 50 : 25;

  setup.shopInv.Bullseye = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      home: 1,
      pharm: 1,
      other: 1,
      shoes: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 1, 1, 1, -2, "Bullseye")),
    leg: clone(setup.clothesGen.stocking(halfCount, 1, 0, 0, -2, "Bullseye")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 1, 0, 1, -2, "Bullseye")),
    bra: clone(setup.clothesGen.bra(count, 1, 0, 1, -2, "Bullseye")),
    top: clone(setup.clothesGen.upperBody(count, 1, 1, 1, -2, "Bullseye")),
    dress: clone(setup.clothesGen.dress(halfCount, 1, 1, 1, -2, "Bullseye")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 0, 0, -2, "Bullseye")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 1, 1, 0, -2, "Bullseye")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 1, 1, 0, -2, "Bullseye")),
    athU: clone(setup.clothesGen.upperBody(halfCount, 7, 0, 0, 1, "Bullseye")),
    athL: clone(setup.clothesGen.lowerBody(halfCount, 7, 0, 0, 1, "Bullseye")),
    niteU: clone(setup.clothesGen.upperBody(halfCount, 5, 1, 0, -2, "Bullseye")),
    niteL: [],
    acc: [],
    bag: [],
    shoes: clone(setup.clothesGen.shoes(halfCount, 1, 1, 0, -2, "Bullseye")),
  };
  setup.shopInv.UniHoe = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 2, 0, 1, -1, "UniHoe")),
    leg: clone(setup.clothesGen.stocking(halfCount, 1, 0, 0, -1, "UniHoe")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 1, 0, 1, -1, "UniHoe")),
    bra: clone(setup.clothesGen.bra(count, 1, 0, 1, -1, "UniHoe")),
    top: clone(setup.clothesGen.upperBody(count, 2, 1, 1, -1, "UniHoe")),
    dress: clone(setup.clothesGen.dress(halfCount, 1, 1, 1, -1, "UniHoe")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 0, 0, -1, "UniHoe")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 2, 1, 0, -1, "UniHoe")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 1, 1, 0, -1, "UniHoe")),
    athU: [],
    athL: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  };
  setup.shopInv.CazzoFottere = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 4, 2, 2, 1, "CazzoFottere")),
    leg: clone(setup.clothesGen.stocking(halfCount, 2, 0, 0, 1, "CazzoFottere")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 5, 0, 2, 1, "CazzoFottere")),
    bra: clone(setup.clothesGen.bra(count, 2, 1, 2, 1, "CazzoFottere")),
    top: clone(setup.clothesGen.upperBody(count, 3, 2, 2, 1, "CazzoFottere")),
    dress: clone(setup.clothesGen.dress(halfCount, 3, 0, 2, 1, "CazzoFottere")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 0, 0, 1, "CazzoFottere")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 4, 2, 0, 1, "CazzoFottere")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 3, 2, 0, 1, "CazzoFottere")),
    athU: [],
    athL: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  };
  setup.shopInv.Cucci = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 4, 2, 2, 2, "Cucci")),
    leg: clone(setup.clothesGen.stocking(halfCount, 2, 0, 0, 2, "Cucci")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 5, 0, 2, 2, "Cucci")),
    bra: clone(setup.clothesGen.bra(count, 2, 1, 2, 2, "Cucci")),
    top: clone(setup.clothesGen.upperBody(count, 4, 2, 2, 2, "Cucci")),
    dress: clone(setup.clothesGen.dress(count, 3, 2, 2, 2, "Cucci")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 0, 0, 2, "Cucci")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 5, 3, 0, 2, "Cucci")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 4, 3, 0, 2, "Cucci")),
    athU: [],
    athL: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  };
  setup.shopInv.ThighGap = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 5, 0, 0, 0, "ThighGap")),
    leg: clone(setup.clothesGen.stocking(halfCount, 1, 0, 2, 0, "ThighGap")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 2, 0, 0, 0, "ThighGap")),
    bra: clone(setup.clothesGen.bra(count, 1, 0, 1, 0, "ThighGap")),
    top: clone(setup.clothesGen.upperBody(count, 2, 0, 0, 0, "ThighGap")),
    dress: clone(setup.clothesGen.dress(halfCount, 1, 1, 0, 0, "ThighGap")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 0, 0, 0, "ThighGap")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 3, 2, 0, 0, "ThighGap")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 3, 2, 0, 0, "ThighGap")),
    athU: [],
    athL: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  };
  setup.shopInv.VaginaSecrets = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: clone(setup.clothesGen.panties(countBig, 6, 2, 2, 0, "VaginaSecrets")),
    leg: clone(setup.clothesGen.stocking(count, 2, 1, 0, 0, "VaginaSecrets")),
    bra: clone(setup.clothesGen.bra(countBig, 3, 1, 2, 0, "VaginaSecrets")),
    swimU: clone(setup.clothesGen.swimTop(halfCount, 5, 3, 0, 0, "VaginaSecrets")),
    swimL: clone(setup.clothesGen.swimBottom(halfCount, 4, 3, 0, 0, "VaginaSecrets")),
    niteU: [],
    niteL: [],
    acc: [],
  };
  setup.shopInv.thotTopic = {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
      shoes: 1,
    },
    panties: clone(setup.clothesGen.panties(count, 2, 0, 4, -1, "thotTopic")),
    leg: clone(setup.clothesGen.stocking(halfCount, 1, 0, 4, -1, "thotTopic")),
    bottom: clone(setup.clothesGen.lowerBody(countBig, 1, 0, 4, -1, "thotTopic")),
    bra: clone(setup.clothesGen.bra(count, 1, 0, 4, -1, "thotTopic")),
    top: clone(setup.clothesGen.upperBody(count, 2, 4, 5, -1, "thotTopic")),
    dress: clone(setup.clothesGen.dress(halfCount, 1, 1, 4, -1, "thotTopic")),
    coat: clone(setup.clothesGen.coat(halfCount, 1, 4, 4, -1, "thotTopic")),
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
    shoes: clone(setup.clothesGen.shoes(halfCount, 3, 0, 8, -1, "thotTopic")),
  };
  setup.shopInv.BallSack = {
    sales: {
      underwear: 1,
      clothes: 1,
      acc: 1,
      all: 1,
      shoes: 1,
    },
    panties: [],
    leg: [],
    bra: clone(setup.clothesGen.bra(count, 4, 0, 0, 1, "BallSack")),
    swimU: clone(setup.clothesGen.swimTop(count, 2, 1, 0, 0, "BallSack")),
    swimL: clone(setup.clothesGen.swimBottom(count, 4, 3, 0, 0, "BallSack")),
    top: clone(setup.clothesGen.upperBody(count, 7, 0, 0, 1, "BallSack")),
    bottom: clone(setup.clothesGen.lowerBody(count, 7, 0, 0, 1, "BallSack")),
    acc: [],
    bag: [],
    shoes: clone(setup.clothesGen.shoes(count, 2, 0, 0, -1, "BallSack")),
  };
  setup.shopInv.Shoegasm = {
    sales: {
      shoes: 1,
    },
    shoes: clone(setup.clothesGen.shoes(50, 0, 0, 0, -1, "Shoegasm")),
  };
  ↂ.storeInv = {
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
    shoes: [],
  };
};


// shopInv -> storeID -> ItemType = Array

setup.shopInv = {
  Bullseye: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      home: 1,
      pharm: 1,
      other: 1,
      all: 1,
      shoes: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
    shoes: [],
  },
  UniHoe: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  },
  CazzoFottere: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  },
  Cucci: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  },
  ThighGap: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
  },
  VaginaSecrets: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bra: [],
    swimU: [],
    swimL: [],
    niteU: [],
    niteL: [],
    acc: [],
  },
  TightThreads: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      shoes: 1,
      acc: 1,
      all: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    swimU: [],
    swimL: [],
    athU: [],
    athL: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
    shoes: [],
  },
  thotTopic: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
      shoes: 1,
    },
    panties: [],
    leg: [],
    bottom: [],
    bra: [],
    top: [],
    dress: [],
    coat: [],
    niteU: [],
    niteL: [],
    acc: [],
    bag: [],
    shoes: [],
  },
  BallSack: {
    sales: {
      underwear: 1,
      clothes: 1,
      coats: 1,
      acc: 1,
      all: 1,
      shoes: 1,
    },
    panties: [],
    leg: [],
    bra: [],
    coat: [],
    swimU: [],
    athU: [],
    athL: [],
    acc: [],
    bag: [],
    shoes: [],
  },
  Shoegasm: {
    sales: {
      shoes: 1,
    },
    shoes: [],
  },
};


